// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6X10Q8gZBEkHMQ8X3czKVE9P3e639w0o',
    appId: '1:726547583949:web:d3b2eae62c588109f6ea84',
    messagingSenderId: '726547583949',
    projectId: 'instagram-df221',
    authDomain: 'instagram-df221.firebaseapp.com',
    storageBucket: 'instagram-df221.appspot.com',
    measurementId: 'G-HKVHJ8XVFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgkOCc0pMJorA1n8telkW5lAcrP47Cqfs',
    appId: '1:726547583949:android:504ab962e8030e17f6ea84',
    messagingSenderId: '726547583949',
    projectId: 'instagram-df221',
    storageBucket: 'instagram-df221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHS-wjo1k8fa4n0HievJ_ddF5brbka644',
    appId: '1:726547583949:ios:4715211984230841f6ea84',
    messagingSenderId: '726547583949',
    projectId: 'instagram-df221',
    storageBucket: 'instagram-df221.appspot.com',
    iosBundleId: 'com.example.ig',
  );
}
